---
title: "Experimental_economics_hw"
author: "shan zhang"
date: "4/25/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, ## Show all R output
  cache = TRUE, ## Cache the results to increase performance.
  message = FALSE ## Suppress messages (e.g. about namespace conflicts)
  ) 
```

### preliminaries
```{r packs, cache=FALSE}
## load pacman
if(!require("pacman")) install.packages("pacman")
## load packages using pacman::p_load
p_load(tidyverse, broom, huxtable, ggplot2, cowplot, estimatr)
theme_set(theme_minimal())
```

### Simulation
```{r sim}
## create a function for simulating data
sim_fun <- function(n) {
  ## initialize an empty data frame
  ite_df <- as_tibble(matrix(ncol = 4, nrow = n))
  ## assign names 
  names(ite_df) <-c("y_1", "y_0", "D", "treat")
  ## populate the variables with simulated data
  ## y_0 is the control outcome, y_1 is the treatment outcome, and assign
  ## treatment 
  ite_df %>%
    mutate(y_1 = rnorm(n, 21500, 5000)) %>%
    mutate(y_0 = rnorm(n, 20000, 5000)) %>%
    ## assign to treatment
    mutate(D = sample(c(0, 1), 
                size = n, 
                replace = TRUE, 
                prob = c(0.5, 0.5))) %>%
   ## treatment effect
    mutate(treat = y_1 - y_0)
}

set.seed(20497)
simu_df <-  sim_fun(10000)
```